name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies and run Cypress tests
      - name: Install dependencies and run Cypress tests
        uses: cypress-io/github-action@v6

      # Upload screenshots (only on test failures)
      - name: Upload screenshots (on failure)
        if: failure() # Upload only if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      # Upload videos
      - name: Upload videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
